<a href="https://colab.research.google.com/github/Bhushan-14/Python/blob/main/Python_11_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
arr3 = np.array([12,3,4,623,34,"Amit","Ram",23])
print(arr3)

['12' '3' '4' '623' '34' 'Amit' 'Ram' '23']


In [6]:
#2D Array
arr4 = np.array([(1,2,3),(4,5,6)])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [7]:
arr4.dtype

dtype('int64')

In [8]:
arr4.size

6

In [10]:
arr4.shape

(2, 3)

In [13]:
arr5 = np.arange(20).reshape(5,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
arr7 = np.arange(18).reshape(2,3,3)
arr7

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [18]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [22]:
a = np.array([2,3,4,5])
b = np.arange(4)

In [23]:
a + b

array([2, 4, 6, 8])

In [24]:
a < 4

array([ True,  True, False, False])

In [26]:
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(2,3,6),(1,3,4)])

In [27]:
x+y

array([[ 3,  5,  9],
       [ 5,  8, 10]])

In [28]:
x*y

array([[ 2,  6, 18],
       [ 4, 15, 24]])

In [29]:
#Random numbers in array
np.random.rand(3,3,)

array([[0.35841359, 0.79153909, 0.66457394],
       [0.01314355, 0.263124  , 0.11874462],
       [0.37156638, 0.29923981, 0.09798843]])

In [30]:
#An array of your choice
#create an array filled with any given value using the np.full()
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [31]:
#np.eye() that returns an array with is along its digonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
a = np.linspace(0,100,20)
a
a.size

4

In [34]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [35]:
a = np.array([3,6,9,12,18,24])

In [38]:
a.reshape(3,2)

array([[ 3,  6],
       [ 9, 12],
       [18, 24]])

In [39]:
arr = np.array([(1,2,3),(4,5,6)])

In [40]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [42]:
a = arr.ravel()

In [43]:
arr2 = np.array([(1,2,3),(4,5,6)])
arr3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])

In [45]:
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.transpose(arr3)

array([[[ 1,  6],
        [ 4,  9]],

       [[ 2,  7],
        [ 5, 10]],

       [[ 3,  8],
        [ 6, 11]]])

In [47]:
a = np.array([1,2,3])
b = np.expand_dims(a,axis = 0)
c = np.expand_dims(a, axis = 1)

In [48]:
np.squeeze(c,axis = 1)

array([1, 2, 3])

In [49]:
arr1 = np.array([12,34,56,78,90,6,9,21])

In [50]:
arr1 [1:8:2]

array([34, 78,  6, 21])

In [51]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [52]:
arr2[1:,:2]

array([[4, 5]])

In [54]:
arr3 = np.array([[[1,2],[3,4],[5,6]],
                 [[7,8],[9,10],[11,12]],
                 [[13,14],[15,16],[17,18]]])
arr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [55]:
arr3[1:,0:,:]

array([[[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])