<a href="https://colab.research.google.com/github/Bhushan-14/Python/blob/main/Python_11_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr3 = np.array([12,3,4,623,34,"Amit","Ram",23])
print(arr3)

['12' '3' '4' '623' '34' 'Amit' 'Ram' '23']


In [ ]:
#2D Array
arr4 = np.array([(1,2,3),(4,5,6)])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr4.dtype

dtype('int64')

In [ ]:
arr4.size

6

In [ ]:
arr4.shape

(2, 3)

In [ ]:
arr5 = np.arange(20).reshape(5,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr7 = np.arange(18).reshape(2,3,3)
arr7

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
a = np.array([2,3,4,5])
b = np.arange(4)

In [ ]:
a + b

array([2, 4, 6, 8])

In [ ]:
a < 4

array([ True,  True, False, False])

In [ ]:
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(2,3,6),(1,3,4)])

In [ ]:
x+y

array([[ 3,  5,  9],
       [ 5,  8, 10]])

In [ ]:
x*y

array([[ 2,  6, 18],
       [ 4, 15, 24]])

In [ ]:
#Random numbers in array
np.random.rand(3,3,)

array([[0.35841359, 0.79153909, 0.66457394],
       [0.01314355, 0.263124  , 0.11874462],
       [0.37156638, 0.29923981, 0.09798843]])

In [ ]:
#An array of your choice
#create an array filled with any given value using the np.full()
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
#np.eye() that returns an array with is along its digonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
a = np.linspace(0,100,20)
a
a.size

4

In [ ]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
a = np.array([3,6,9,12,18,24])

In [ ]:
a.reshape(3,2)

array([[ 3,  6],
       [ 9, 12],
       [18, 24]])

In [ ]:
arr = np.array([(1,2,3),(4,5,6)])

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = arr.ravel()

In [ ]:
arr2 = np.array([(1,2,3),(4,5,6)])
arr3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])

In [ ]:
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.transpose(arr3)

array([[[ 1,  6],
        [ 4,  9]],

       [[ 2,  7],
        [ 5, 10]],

       [[ 3,  8],
        [ 6, 11]]])

In [ ]:
a = np.array([1,2,3])
b = np.expand_dims(a,axis = 0)
c = np.expand_dims(a, axis = 1)

In [ ]:
np.squeeze(c,axis = 1)

array([1, 2, 3])

In [ ]:
arr1 = np.array([12,34,56,78,90,6,9,21])

In [ ]:
arr1 [1:8:2]

array([34, 78,  6, 21])

In [ ]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [ ]:
arr2[1:,:2]

array([[4, 5]])

In [ ]:
arr3 = np.array([[[1,2],[3,4],[5,6]],
                 [[7,8],[9,10],[11,12]],
                 [[13,14],[15,16],[17,18]]])
arr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
arr3[1:,0:,:]

array([[[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
import numpy as np

In [ ]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
a = np.array([3,6,9,12,18,24])
print("Three rows: ",'\n',np.reshape(a,(3,-1)))
print("Three columns: ",'\n',np.reshape(a,(-1,3)))

Three rows:  
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns:  
 [[ 3  6  9]
 [12 18 24]]


In [ ]:
a = np.ones((3,3))
b = a.flatten()
c = a.ravel()

In [ ]:
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)

c.shape

(3, 1)

In [ ]:
a = np.array([[1,2,3],[6,7,8],[11,12,13]])
print(a)
np.flip(a,axis=0)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


array([[11, 12, 13],
       [ 6,  7,  8],
       [ 1,  2,  3]])

In [ ]:
a = np.arange(0,5)
b = np.arange(5,10)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))

c

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [ ]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)

np.concatenate((a,b),axis = 1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
a = np.array([[1,2],[3,4]])
np.append(a,[[5,6],[7,8]],axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.array([1,2,3])

b = np.array([2,3,4])

c = a+b
c

array([3, 5, 7])

In [ ]:
A = np.array([[1,2,3],[4,0,7]])

B = np.array([(1,1,1),(2,3,2)])
A+B

array([[2, 3, 4],
       [6, 3, 9]])

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
y

array([1, 4, 5])

In [ ]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
y

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
z = x[1:4,1:3]
y = x[1:4,[1,2]]
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [ ]:
a = np.arange(1,6)
b = np.arange(6,1)

In [ ]:
print("Subtract: ",a-5)
print("Multiply: ",a*5)
print("Divide: ",a/5)
print("Power: ",a**5)
print("Remainder: ",a%5)

Subtract:  [-4 -3 -2 -1  0]
Multiply:  [ 5 10 15 20 25]
Divide:  [0.2 0.4 0.6 0.8 1. ]
Power:  [   1   32  243 1024 3125]
Remainder:  [1 2 3 4 0]


In [ ]:
a = np.arange(5,15,2)
print("Mean: ",np.mean(a))
print("Standara Deviation: ",np.std(a))
print("Median: ",np.median(a))

Mean:  9.0
Standara Deviation:  2.8284271247461903
Median:  9.0


In [ ]:
a= np.array([[1,6],[4,3]])
print("Min: ",np.min(a,axis=0))
print("Max: ",np.max(a,axis=1))

Min:  [1 3]
Max:  [6 4]


In [ ]:
a = np.arange(0,60,5).reshape(3,4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [ ]:
for x in np.nditer(a):
  print(x,end="")

0510152025303540455055

In [ ]:
a.T

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [ ]:
np.arange(8).reshape(2,4)
arr = np.arange(8)
np.reshape(arr,(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a = np.arange(8).reshape(2,4)
for x in a.flat:
  print(x,end=" ")

0 1 2 3 4 5 6 7 

In [ ]:
a = np.arange(8).reshape(2,4)
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
a = np.arange(8).reshape(2,4)
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
a = np.arange(12).reshape(3,4)
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = np.arange(8).reshape(2,2,2)
print(a)
print("*"*20)
print(np.rollaxis(a,2))
print("*"*20)
print(np.rollaxis(a,2,1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
********************
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
********************
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [ ]:
a = np.arange(8).reshape(2,2,2)
print(a)
np.swapaxes(a,2,0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
b = np.broadcast(x,y)
for a in b:
  print(a,end="")

(1, 4)(1, 5)(1, 6)(2, 4)(2, 5)(2, 6)(3, 4)(3, 5)(3, 6)

In [ ]:
a = np.arange(4).reshape(1,4)
np.broadcast_to(a,(4,4))


array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
x = np.array([[1,2],[3,4]])
np.expand_dims(x,axis = 1)

array([[[1, 2]],

       [[3, 4]]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate((a,b),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.arange(9)
np.split(a,[4,6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [ ]:
a = np.arange(16).reshape(4,4)
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.resize(a,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])